#!/bin/sh
# 05-whitelist.sh — Generate ModSecurity IP whitelist from WHITELIST_CIDRS.
# Runs inside the WAF container before nginx starts.
# Sourced from WHITELIST_CIDRS in .env (space or comma separated CIDRs).

DEST="/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-WHITELIST.conf"

# Always whitelist localhost only.
# Do NOT add Docker bridge subnets here — that would bypass WAF inspection for
# all upstream traffic (NPM, waf-tester, etc.) and make the WAF useless.
# Real client IPs are resolved via X-Real-IP (set REAL_IP_HEADER in compose).
ALWAYS="127.0.0.1,::1"

EXTRA="${WHITELIST_CIDRS:-}"

if [ -n "$EXTRA" ]; then
    # Normalise: replace spaces/semicolons with commas, strip extras
    EXTRA=$(echo "$EXTRA" | tr ' ;' ',,' | tr -s ',')
    IPS="${ALWAYS},${EXTRA}"
else
    IPS="${ALWAYS}"
fi

echo "[05-whitelist] Trusted IPs: ${IPS}"

cat > "$DEST" << EOF
# Auto-generated by 05-whitelist.sh from WHITELIST_CIDRS env var.
# Do not edit — update WHITELIST_CIDRS in .env and restart the waf container.

SecRule REMOTE_ADDR "@ipMatch ${IPS}" \\
    "id:900001,\\
    phase:1,\\
    pass,\\
    nolog,\\
    ctl:ruleEngine=Off"
EOF
