[Definition]
failregex = ^\[.*\] - \d+ \d+ - \S+ \S+ \S+ ".*" \[Client <HOST>\] .* "(?:masscan|nikto|nmap|sqlmap|zgrab|nuclei|dirbuster|gobuster|ffuf|wfuzz|hydra|medusa|burp|acunetix|nessus|openvas)[^"]*"
ignoreregex =
