#!/bin/sh
# Runs before fail2ban starts (via s6/cont-init.d).
# Writes a jail.d override that adds WHITELIST_CIDRS to ignoreip.
# This avoids %(ENV[...])s interpolation which fail2ban no longer supports.

OUTFILE="/data/jail.d/10-whitelist.conf"

if [ -z "${WHITELIST_CIDRS}" ]; then
    # No extra CIDRs — remove any stale override and exit
    rm -f "${OUTFILE}"
    exit 0
fi

mkdir -p /data/jail.d

# Normalise: commas → spaces
CIDRS="$(echo "${WHITELIST_CIDRS}" | tr ',' ' ')"

cat > "${OUTFILE}" << EOF
# Auto-generated by cont-init.d/10-whitelist.sh — do not edit manually.
# Source: WHITELIST_CIDRS env var in docker-compose / .env

[DEFAULT]
ignoreip = 127.0.0.1/8 ::1 172.16.0.0/12 ${CIDRS}
EOF

echo "fail2ban whitelist: ignoreip set to: 127.0.0.1/8 ::1 172.16.0.0/12 ${CIDRS}"
